# Site settings
name: iolaSay
email: fwl1998@foxmail.com
author: iola1999
url: https://678234.xyz
resume_site: https://678234.xyz
github: https://github.com/iola1999
baseurl: ""
description: 影言
meta_description: 影言;个人博客
motto:  
banner:  

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: iola1999

# Build settings
markdown: kramdown

baidu_analysis: 0000000000000000000000000000

# 20190517 Disqus control
layout: default
comments: true